export const adminUi = {
  brand: 'لوحة التحكم',
  nav: {
    dashboard: 'الرئيسية',
    articles: 'المقالات',
    projects: 'المشاريع',
    site: 'إعدادات الموقع',
    social: 'وسائل التواصل',
    profile: 'الملف الشخصي',
    deploy: 'النشر',
    logout: 'تسجيل الخروج',
    viewSite: 'عرض الموقع',
  },
  common: {
    save: 'حفظ',
    saving: 'جارٍ الحفظ...',
    delete: 'حذف',
    cancel: 'إلغاء',
    create: 'إنشاء',
    edit: 'تعديل',
    locale: 'اللغة',
    slug: 'المعرّف',
    title: 'العنوان',
    status: 'الحالة',
    actions: 'إجراءات',
    success: 'تم الحفظ بنجاح',
    error: 'حدث خطأ',
    loading: 'جارٍ التحميل...',
    confirmDelete: 'هل أنت متأكد من الحذف؟',
    deploy: 'نشر الآن',
    deploying: 'جارٍ النشر...',
  },
  login: {
    title: 'تسجيل الدخول',
    subtitle: 'لوحة إدارة المحتوى',
    password: 'كلمة المرور',
    submit: 'دخول',
    error: 'بيانات الدخول غير صحيحة',
  },
  dashboard: {
    title: 'لوحة التحكم',
    subtitle: 'إدارة المحتوى والنشر عبر Git',
    githubConnected: 'GitHub متصل',
    githubDisconnected: 'GitHub غير مضبوط',
    lastDeploy: 'آخر نشر',
  },
} as const;
