export const adminUi = {
  brand: 'لوحة التحكم',
  sections: {
    main: 'الرئيسية',
    content: 'المحتوى',
    settings: 'الإعدادات',
    system: 'النظام',
  },
  nav: {
    dashboard: 'لوحة المعلومات',
    articles: 'المقالات',
    projects: 'المشاريع',
    site: 'إعدادات الموقع',
    social: 'وسائل التواصل',
    profile: 'الملف الشخصي',
    deploy: 'النشر',
    logout: 'تسجيل الخروج',
    viewSite: 'عرض الموقع',
  },
  common: {
    save: 'حفظ التغييرات',
    saving: 'جارٍ الحفظ...',
    delete: 'حذف',
    cancel: 'إلغاء',
    create: 'إضافة جديد',
    edit: 'تعديل',
    locale: 'اللغة',
    slug: 'المعرّف',
    title: 'العنوان',
    category: 'التصنيف',
    date: 'التاريخ',
    status: 'الحالة',
    actions: 'إجراءات',
    success: 'تم الحفظ بنجاح',
    error: 'حدث خطأ، حاول مرة أخرى',
    loading: 'جارٍ التحميل...',
    confirmDelete: 'هل أنت متأكد من الحذف؟',
    deploy: 'نشر الآن',
    deploying: 'جارٍ النشر...',
    search: 'بحث...',
    noData: 'لا توجد بيانات',
    readOnly: 'قراءة فقط',
    sourceLocal: 'محلي',
    sourceGithub: 'GitHub',
  },
  login: {
    title: 'مرحباً بعودتك',
    subtitle: 'سجّل الدخول لإدارة محتوى موقعك',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    submit: 'تسجيل الدخول',
    error: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    errors: {
      invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      captcha_required: 'يرجى إكمال التحقق الأمني (Turnstile)',
      captcha_failed: 'فشل التحقق الأمني، حاول مرة أخرى',
      rate_limited: 'محاولات كثيرة، انتظر دقيقة ثم حاول مجدداً',
      admin_not_configured: 'لوحة التحكم غير مهيأة على الخادم',
      turnstile_not_configured: 'التحقق الأمني غير مهيأ على الخادم',
      bad_request: 'طلب غير صالح، استخدم نموذج تسجيل الدخول',
    },
    heroTitle: 'إدارة احترافية لمحتوى Portfolio',
    heroText: 'عدّل المقالات والمشاريع والإعدادات، ثم انشر التغييرات بضغطة واحدة عبر GitHub Actions.',
    feature1: 'تحرير متعدد اللغات (عربي / English / Français)',
    feature2: 'نشر آمن عبر Cloudflare Workers',
    feature3: 'حماية بـ Turnstile وجلسات مشفّرة',
  },
  dashboard: {
    title: 'لوحة المعلومات',
    subtitle: 'نظرة عامة على المحتوى وحالة النشر',
    githubConnected: 'GitHub متصل',
    githubDisconnected: 'GitHub غير مضبوط',
    lastDeploy: 'آخر نشر',
    totalArticles: 'إجمالي المقالات',
    totalProjects: 'إجمالي المشاريع',
    locales: 'اللغات',
    quickActions: 'إجراءات سريعة',
    systemStatus: 'حالة النظام',
    visitors: 'الزوار',
    todayViews: 'مشاهدات اليوم',
    todayVisitors: 'زوار اليوم',
    weekViews: 'مشاهدات 7 أيام',
    weekVisitors: 'زوار 7 أيام',
    topPages: 'أكثر الصفحات زيارة',
    topReferrers: 'مصادر الزيارات',
    trackingActive: 'التتبع مفعّل',
    trackingGa4: 'Google Analytics 4',
    trackingCf: 'Cloudflare Analytics',
    trackingInternal: 'تحليلات داخلية',
    openGa: 'فتح Google Analytics',
    cachedStats: 'محمّل من الذاكرة المؤقتة',
    refreshStats: 'تحديث الإحصائيات',
    noVisitorData: 'لا توجد بيانات زوار بعد',
  },
} as const;
